# Recommended to be disabled on OSX (https://yarnpkg.com/configuration/yarnrc/#enableGlobalCache)
enableGlobalCache: false

# Enforces the original linker (https://yarnpkg.com/configuration/yarnrc/#nodeLinker)
nodeLinker: node-modules # pnp

yarnPath: '.yarn/releases/yarn-berry.cjs'
