enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  coolfiresolutions:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.pkg.github.com'

yarnPath: .yarn/releases/yarn-3.0.0.cjs
