name: PR Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - ready_for_review

# concurrency:
#   group: ${{ github.head_ref }}
#   cancel-in-progress: true

jobs:
  check_changelog_label:
    name: Check for label
    runs-on: ubuntu-latest
    if: ${{!contains( github.event.pull_request.labels.*.name, 'skip-release')}}
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: major,minor,patch,internal,documentation,tests,dependencies,performance
          repo_token: ${{ secrets.GITHUB_TOKEN }}
  check_pr_title:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
            removal
          # scopes: |
          #   deps
          #   devDeps
          #   github-actions
