name: Check

on:
  push:
    branches:
      - main
      - 'renovate-custom/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  check:
    name: Lint, Test, Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Load Node version based on .nvmrc file
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - uses: actions/setup-node@v3.1.0
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          cache: 'yarn'
          check-latest: true

      # Load Dependency Cache and Trigger Install
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --coverage

      - name: Upload coverage to Codecov
        if: ${{ always() }}
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build
        run: yarn build
