name: Renovate
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0/15 * * * *'

concurrency:
  group: renovate
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.111.1
        env:
          LOG_LEVEL: 'debug'
        with:
          configurationFile: ./renovate.json
          token: ${{ secrets.GH_TOKEN }}
